"""Add M-Pesa payment support

Revision ID: b4296c220944
Revises: fce2a2e238bb
Create Date: 2025-12-27 17:43:13.213508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4296c220944'
down_revision = 'fce2a2e238bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=20), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('raw_callback_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('mpesa_receipt_number')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_result_desc', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['mpesa_receipt_number'])
        batch_op.create_unique_constraint(None, ['checkout_request_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_result_desc')
        batch_op.drop_column('payment_result_code')
        batch_op.drop_column('last_payment_attempt')
        batch_op.drop_column('payment_attempts')
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('payment_phone_number')
        batch_op.drop_column('payment_status')

    op.drop_table('payments')
    op.drop_table('payment_logs')
    # ### end Alembic commands ###
